Traceback (most recent call last):
  File "/Users/unimos/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/unimos/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/unimos/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/unimos/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/unimos/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/unimos/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/unimos/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/unimos/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ipmag.aniso_magic(infile='dike_specimens.txt',dir_path='data_files/aniso_magic',
       iboot=1,ihext=0,ivec=1,PDir=[120,10],ipar=1, save_plots=False) # compare dike directions with plane of dike with pole of 120,10
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
Input [0;32mIn [5][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m [43mipmag[49m[38;5;241;43m.[39;49m[43maniso_magic[49m[43m([49m[43minfile[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mdike_specimens.txt[39;49m[38;5;124;43m'[39;49m[43m,[49m[43mdir_path[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mdata_files/aniso_magic[39;49m[38;5;124;43m'[39;49m[43m,[49m
[1;32m      2[0m [43m       [49m[43miboot[49m[38;5;241;43m=[39;49m[38;5;241;43m1[39;49m[43m,[49m[43mihext[49m[38;5;241;43m=[39;49m[38;5;241;43m0[39;49m[43m,[49m[43mivec[49m[38;5;241;43m=[39;49m[38;5;241;43m1[39;49m[43m,[49m[43mPDir[49m[38;5;241;43m=[39;49m[43m[[49m[38;5;241;43m120[39;49m[43m,[49m[38;5;241;43m10[39;49m[43m][49m[43m,[49m[43mipar[49m[38;5;241;43m=[39;49m[38;5;241;43m1[39;49m[43m,[49m[43m [49m[43msave_plots[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m)[49m

File [0;32m~/0000_Github/PmagPy/pmagpy/ipmag.py:10481[0m, in [0;36maniso_magic[0;34m(infile, samp_file, site_file, verbose, ipar, ihext, ivec, isite, iloc, iboot, vec, Dir, PDir, crd, num_bootstraps, dir_path, fignum, save_plots, interactive, fmt, contribution, image_records)[0m
[1;32m  10479[0m [38;5;66;03m# get other data[39;00m
[1;32m  10480[0m con[38;5;241m.[39mpropagate_location_to_specimens()
[0;32m> 10481[0m spec_container [38;5;241m=[39m [43mcon[49m[38;5;241;43m.[39;49m[43mtables[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mspecimens[39;49m[38;5;124;43m'[39;49m[43m][49m
[1;32m  10482[0m spec_df [38;5;241m=[39m spec_container[38;5;241m.[39mdf
[1;32m  10483[0m [38;5;66;03m# use only anisotropy records[39;00m

[0;31mKeyError[0m: 'specimens'
KeyError: 'specimens'

